### ISSUE TITLE
Empty text field throws 

### ISSUE THREAD

**Issue by mantzuri** [kiran5232/TextInputLayout#1]
If no text is entered  and the user click away, we get the following error:

> [__NSCFNumber pointSize]: unrecognized selector sent to instance 0xb000000000000115

**Comment by mantzuri** [comment]
Well, solved:
Line 68 in kTextFiledPlaceHolder.swift
replaced :  `if (self.placeholder != nil)  {...`
with: `if (self.placeholder != nil) && (self.text != "")  {....`

**Comment by KiranPatelSpaceo** [comment]
Hey mantzuri,

I got your mail now.

Thanks for finding and solving issue.
Thank you so much Appreciate !
